### ISSUE TITLE
error numbers are not extracted from wrapped errors

### ISSUE THREAD

**Issue by fhryanc** [bombsimon/mysql-error-numbers#3]
@bombsimon, thanks for your work on this library!

I ran into a case where I need to pull the MySQL error number from an error that has already been wrapped in another error. Switching `FromError()` from a direct type assertion to `errors.As()` would support both `*mysql.MySQLError` errors and those that have been wrapped.

https://github.com/bombsimon/mysql-error-numbers/blob/720ea9343e1ee008ca0d88707014f8f266e23994/mysql_error_numbers.go#L28

**Comment by bombsimon** [comment]
Thank you!

I haven't used this in a long time but if you can try [v2.0.0-rc3](https://github.com/bombsimon/mysql-error-numbers/releases/tag/v2.0.0-rc3) and confirm it's working as indented I can do a proper stable v2 release!

**Comment by fhryanc** [comment]
> I haven't used this in a long time but if you can try [v2.0.0-rc3](https://github.com/bombsimon/mysql-error-numbers/releases/tag/v2.0.0-rc3) and confirm it's working as indented I can do a proper stable v2 release!

[v2.0.0-rc3](https://github.com/bombsimon/mysql-error-numbers/releases/tag/v2.0.0-rc3) works for me, though it did force a Go tooling update to `1.23`. Unless the update was required by one of your dependencies, you might consider dropping back to `1.22` to give your consumers a little flexibility.

Other than that, thanks for the update! A stable v2 will be nice. :)

**Comment by bombsimon** [comment]
Thanks! Downgraded the dependency and made a stable [v2.0.0](https://github.com/bombsimon/mysql-error-numbers/releases/tag/v2.0.0) release

**Comment by fhryanc** [comment]
Nice! Thanks for your quick help. :)
